
```{r}
dbGetQuery(
  other_counties, 
  "select distinct product_name from forecasts_all_counties where product_name like 'labetalol %'") %>% pull(product_name)
```

```{r}
dbGetQuery(
  other_counties, 
  "select distinct county, product_name from forecasts_all_counties where product_name like 'labetalol %'")


search_data <- function(db_conn, table_name, search_key, product_column = "item_description_name_form_strength") {
  
  query <- glue(
    "
    SELECT 
      county,
      {product_column} as product_name,
      pack_size,
      --ROUND(AVG(price_kes)) as avg_price_kes,
      ROUND(SUM(quantity_required_for_period_specified_above), 0) as quantity_required
    FROM {table_name}
    WHERE 
      {product_column} LIKE '{search_key}'
    GROUP BY {product_column}, county
    "
  )
  
  res <- dbGetQuery(
    db_conn, query
  )
  return(res)
}


search_data(other_counties, "forecasts_all_counties", "Hydra%", "product_name")
```



# 2020

```{r}
library(openxlsx)
library(readxl)
library(fs)

files <- dir_ls("2021-Quantification-Results/xlsx-files/")


files[1] %>% excel_sheets() %>% as_tibble() %>% filter(value != "All Counties") %>% pull(value)

map(
  files, ~ excel_sheets(.x) %>% as_tibble() %>% filter(!value %>% str_detect("All")) %>% pull(value)
)

df <- files[1] %>% 
  read_excel(sheet = files[1] %>% excel_sheets() %>% as_tibble() %>% filter(value %>% str_detect("All")) %>% pull(value)) %>% 
   clean_names()

df <- map_df(
  files,
  ~ read_excel(.x, sheet = .x %>% excel_sheets() %>% as_tibble() %>% filter(value %>% str_detect("All")) %>% pull(value))
) %>% clean_names()


write_csv(df, "2021-Quantification-Results/xlsx-files/all")


```


```{r}
product_str


df %>% 
  filter(item %in% product_list) %>% 
  summarise(
    total_quantity_required = round(sum(total_quantity_required, na.rm = TRUE)),
    .by = c(item, pack_size, county)
  ) %>% 
  rename(product_name = item) -> df_summary
  
df_summary %>% 
  pivot_wider(names_from = county, values_from = total_quantity_required) %>% 
  write.xlsx(
    "2021-Quantification-Results/results/mnch_forecasts.xlsx"
  )

df_summary %>% 
  distinct(product_name)

product_list %>% as_tibble() %>% 
  anti_join(df_summary, by = join_by(value == product_name)) %>% 
  write.xlsx("2021-Quantification-Results/xlsx-files/missing_mnch_from_forecasts.xlsx")
```


```{r}
df_summary %>% 
  pivot_wider(names_from = county, values_from = total_quantity_required)
```


```{r}
dis <- sqlite_conn("Data-API/data")

dbListTables(dis)

dbWriteTable(dis, "data", response %>% mutate(period = period %>% as.character()), append = T)

dbReadTable(dis, "data") 
  
```


```{r}
library(httr)

url <- "http://127.0.0.1:8000/data"
params <- list(
  analytic = "Iron and Folic acid supplementation (Tablet)",
  org_unit = "Meru"
)

response <- GET(url, query = params, add_headers(accept = "application/json"))

# Print the content of the response
test <- content(response, "text") %>% fromJSON()

test$data
```

```{r}
pacman::p_load(timetk)


response %>% 
  filter(
    analytic == "Chlorhexidine gel, 7.1% (as digluconate) (20 g tube) (Tube)",
    org_unit == "Kenya"
  ) %>% 
  arrange(period) %>% 
  tk_anomaly_diagnostics(period, value)
```




```{r}
library(timetk)


response %>% 
  unite("id", analytic, org_unit,  sep = "__") %>% 
  filter(
    id == "Oxytocin Injection 10 I.U. (Ampoule)__Kenya"
  ) %>% 
  plot_time_series(period, value, .legend_show = T, .title = "Time Series Plot for Oxytocin Injection 10 I.U. (Ampoule)__Kenya")

```



```{r}
response %>% 
  unite("id", analytic, org_unit,  sep = "__") %>% 
  filter(
    id == "Oxytocin Injection 10 I.U. (Ampoule)__Kenya"
  ) %>% 
  plot_anomaly_diagnostics(period, value, .legend_show = T, .title = "Time Series Plot for Oxytocin Injection 10 I.U. (Ampoule)__Kenya")

```


```{r}
anomaly_input <- response %>% 
  unite("id", analytic, org_unit,  sep = "__")

anomalized_df <- anomaly_input %>% 
  group_by(id) %>% 
  anomalize(period, value)

anomalized_df %>% 
  separate(id, into = c("analytic", "org_unit"), sep = "__") %>% 
  write_csv("data/mnch_moh_647_data_anomalized.csv")
  filter(analytic == "Oxytocin Injection 10 I.U. (Ampoule)", org_unit == "Kenya") %>% 
  plot_anomalies_cleaned(period)
  
anomalized_df %>% 
  mutate(final_value = case_when(anomaly == "Yes" ~ trend, .default = observed))

anomalized_df %>%
        transmute(ds = period, y = round(observed_clean)) %>%
        arrange(ds)
```












































